/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActiveMembersList: typeof import('./components/active/ActiveMembersList.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AverageSalaryChart: typeof import('./components/dashboard/AverageSalaryChart.vue')['default']
    BarGraph: typeof import('./components/dashboard/BarGraph.vue')['default']
    CountCards: typeof import('./components/dashboard/CountCards.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginCard: typeof import('./components/login/LoginCard.vue')['default']
    MemberProfile: typeof import('./components/active/MemberProfileDialog.vue')['default']
    MemberProfileDialog: typeof import('./components/active/MemberProfileDialog.vue')['default']
    PieChart: typeof import('./components/dashboard/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VeiLoader: typeof import('./components/global/loader/VeiLoader.vue')['default']
    WorkspaceList: typeof import('./components/workspace/WorkspaceList.vue')['default']
    WorkspaceUsersDialog: typeof import('./components/workspace/WorkspaceUsersDialog.vue')['default']
  }
}
