/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginCard: typeof import('./components/login/LoginCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WorkspaceList: typeof import('./components/workspace/WorkspaceList.vue')['default']
    WorkspaceUsersDialog: typeof import('./components/workspace/WorkspaceUsersDialog.vue')['default']
  }
}
